-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: 3fa02652357ff0dbb42b5bc78c673b7bc105fcf3
    hooks:
    -   id: check-ast
    -   id: check-merge-conflict
    -   id: fix-encoding-pragma
    -   id: autopep8-wrapper
    -   id: flake8
        args:
        - --config=tox.ini
