site_name: tunl
theme_dir: glsh
repo_url: https://github.com/mattvonrocketstein/tunl.git
site_author: mvr
pages:
- 'Home': 'index.md'
- 'Installation': 'install.md'
- 'Configuration': 'configuration.md'
- 'Usage': 'usage.md'
- 'Contributing': 'contributing.md'
- 'API Reference': 'api/index.html'
