site_name: tunl
theme_dir: glsh
repo_url: https://github.com/mattvonrocketstein/tunl.git
site_author: mvr
pages:
- 'Home': 'index.md'
- 'Installation': 'install.md'
- 'Configuration': 'configuration.md'
- 'Command Usage': 'usage.md'
- 'Programmatic Usage': 'devs.md'
- 'API Reference': 'API.md'
